# Generated by Django 4.2.4 on 2023-08-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empName', models.CharField(max_length=75)),
                ('empDesignation', models.CharField(max_length=50)),
                ('empCTC', models.DecimalField(decimal_places=2, max_digits=10)),
                ('empAddress', models.CharField(max_length=150)),
                ('empMobile', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
